######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/mnt/storage-brno12-cerit/nfs4/home/andrea_kochova/BUSCO/7busco/summaries/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('7busco_032', '7busco_032', '7busco_032', '7busco_032', '7busco_020', '7busco_020', '7busco_020', '7busco_020', '7busco_033', '7busco_033', '7busco_033', '7busco_033', '7busco_041', '7busco_041', '7busco_041', '7busco_041', '7busco_043', '7busco_043', '7busco_043', '7busco_043', '7busco_068', '7busco_068', '7busco_068', '7busco_068', '7busco_001', '7busco_001', '7busco_001', '7busco_001', '7busco_072', '7busco_072', '7busco_072', '7busco_072', '7busco_073', '7busco_073', '7busco_073', '7busco_073', '7busco_005', '7busco_005', '7busco_005', '7busco_005', '7busco_002', '7busco_002', '7busco_002', '7busco_002', '7busco_023', '7busco_023', '7busco_023', '7busco_023', '7busco_013', '7busco_013', '7busco_013', '7busco_013', '7busco_036', '7busco_036', '7busco_036', '7busco_036', '7busco_042', '7busco_042', '7busco_042', '7busco_042', '7busco_047', '7busco_047', '7busco_047', '7busco_047', '7busco_075', '7busco_075', '7busco_075', '7busco_075', '7busco_040', '7busco_040', '7busco_040', '7busco_040', '7busco_048', '7busco_048', '7busco_048', '7busco_048', '7busco_011', '7busco_011', '7busco_011', '7busco_011', '7busco_045', '7busco_045', '7busco_045', '7busco_045', '7busco_074', '7busco_074', '7busco_074', '7busco_074', '7busco_061', '7busco_061', '7busco_061', '7busco_061', '7busco_065', '7busco_065', '7busco_065', '7busco_065', '7busco_004', '7busco_004', '7busco_004', '7busco_004', '7busco_003', '7busco_003', '7busco_003', '7busco_003')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(7.3, 0.0, 12.9, 79.8, 83.9, 0.0, 4.8, 11.3, 0.0, 0.0, 0.0, 100.0, 42.7, 0.0, 16.1, 41.2, 39.5, 0.0, 16.9, 43.6, 53.2, 0.0, 16.1, 30.7, 83.9, 0.0, 4.8, 11.3, 0.0, 0.0, 0.0, 100.0, 65.3, 0.0, 10.5, 24.2, 37.1, 46.0, 6.5, 10.4, 25.8, 58.9, 5.6, 9.7, 0.0, 0.0, 0.0, 100.0, 31.5, 0.0, 21.8, 46.7, 86.3, 0.0, 2.4, 11.3, 15.3, 0.0, 16.9, 67.8, 81.5, 0.0, 2.4, 16.1, 82.3, 0.0, 6.5, 11.2, 46.0, 37.9, 5.6, 10.5, 86.3, 0.0, 2.4, 11.3, 83.1, 0.0, 5.6, 11.3, 83.9, 0.0, 4.8, 11.3, 54.0, 0.0, 17.7, 28.3, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 3.2, 96.8, 28.2, 0.0, 21.8, 50.0, 85.5, 0.0, 2.4, 12.1)
my_values <- c(9, 0, 16, 99, 104, 0, 6, 14, 0, 0, 0, 124, 53, 0, 20, 51, 49, 0, 21, 54, 66, 0, 20, 38, 104, 0, 6, 14, 0, 0, 0, 124, 81, 0, 13, 30, 46, 57, 8, 13, 32, 73, 7, 12, 0, 0, 0, 124, 39, 0, 27, 58, 107, 0, 3, 14, 19, 0, 21, 84, 101, 0, 3, 20, 102, 0, 8, 14, 57, 47, 7, 13, 107, 0, 3, 14, 103, 0, 7, 14, 104, 0, 6, 14, 67, 0, 22, 35, 107, 0, 3, 14, 0, 0, 4, 120, 35, 0, 27, 62, 106, 0, 3, 15)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
