######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/mnt/storage-brno12-cerit/nfs4/home/andrea_kochova/BUSCO/3busco/2ver/summaries/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('busco3_ver2_PML045', 'busco3_ver2_PML045', 'busco3_ver2_PML045', 'busco3_ver2_PML045', 'busco3_ver2_PML013', 'busco3_ver2_PML013', 'busco3_ver2_PML013', 'busco3_ver2_PML013', 'busco3_ver2_PML004', 'busco3_ver2_PML004', 'busco3_ver2_PML004', 'busco3_ver2_PML004', 'busco3_ver2_PML074', 'busco3_ver2_PML074', 'busco3_ver2_PML074', 'busco3_ver2_PML074', 'busco3_ver2_PML005', 'busco3_ver2_PML005', 'busco3_ver2_PML005', 'busco3_ver2_PML005', 'busco3_ver2_PML075', 'busco3_ver2_PML075', 'busco3_ver2_PML075', 'busco3_ver2_PML075', 'busco3_ver2_PML023', 'busco3_ver2_PML023', 'busco3_ver2_PML023', 'busco3_ver2_PML023', 'busco3_ver2_PML020', 'busco3_ver2_PML020', 'busco3_ver2_PML020', 'busco3_ver2_PML020', 'busco3_ver2_PML011', 'busco3_ver2_PML011', 'busco3_ver2_PML011', 'busco3_ver2_PML011', 'busco3_ver2_PML036', 'busco3_ver2_PML036', 'busco3_ver2_PML036', 'busco3_ver2_PML036', 'busco3_ver2_PML042', 'busco3_ver2_PML042', 'busco3_ver2_PML042', 'busco3_ver2_PML042', 'busco3_ver2_PML003', 'busco3_ver2_PML003', 'busco3_ver2_PML003', 'busco3_ver2_PML003', 'busco3_ver2_PML040', 'busco3_ver2_PML040', 'busco3_ver2_PML040', 'busco3_ver2_PML040', 'busco3_ver2_PML043', 'busco3_ver2_PML043', 'busco3_ver2_PML043', 'busco3_ver2_PML043', 'busco3_ver2_PML001', 'busco3_ver2_PML001', 'busco3_ver2_PML001', 'busco3_ver2_PML001', 'busco3_ver2_PML041', 'busco3_ver2_PML041', 'busco3_ver2_PML041', 'busco3_ver2_PML041', 'busco3_ver2_PML032', 'busco3_ver2_PML032', 'busco3_ver2_PML032', 'busco3_ver2_PML032', 'busco3_ver2_PML002', 'busco3_ver2_PML002', 'busco3_ver2_PML002', 'busco3_ver2_PML002', 'busco3_ver2_PML065', 'busco3_ver2_PML065', 'busco3_ver2_PML065', 'busco3_ver2_PML065', 'busco3_ver2_PML068', 'busco3_ver2_PML068', 'busco3_ver2_PML068', 'busco3_ver2_PML068', 'busco3_ver2_PML061', 'busco3_ver2_PML061', 'busco3_ver2_PML061', 'busco3_ver2_PML061', 'busco3_ver2_PML048', 'busco3_ver2_PML048', 'busco3_ver2_PML048', 'busco3_ver2_PML048', 'busco3_ver2_PML033', 'busco3_ver2_PML033', 'busco3_ver2_PML033', 'busco3_ver2_PML033', 'busco3_ver2_PML072', 'busco3_ver2_PML072', 'busco3_ver2_PML072', 'busco3_ver2_PML072', 'busco3_ver2_PML073', 'busco3_ver2_PML073', 'busco3_ver2_PML073', 'busco3_ver2_PML073', 'busco3_ver2_PML047', 'busco3_ver2_PML047', 'busco3_ver2_PML047', 'busco3_ver2_PML047')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(83.9, 0.0, 4.8, 11.3, 37.9, 0.0, 25.8, 36.3, 39.5, 0.0, 27.4, 33.1, 61.3, 0.0, 20.2, 18.5, 29.0, 54.8, 6.5, 9.7, 82.3, 0.0, 6.5, 11.2, 0.0, 0.0, 0.0, 100.0, 83.9, 0.0, 4.8, 11.3, 83.1, 0.0, 5.6, 11.3, 86.3, 0.0, 2.4, 11.3, 19.4, 0.0, 23.4, 57.2, 86.3, 0.0, 2.4, 11.3, 37.9, 46.8, 5.6, 9.7, 50.0, 0.0, 25.0, 25.0, 83.1, 0.0, 5.6, 11.3, 56.5, 0.0, 17.7, 25.8, 9.7, 0.0, 17.7, 72.6, 20.2, 64.5, 5.6, 9.7, 0.0, 0.0, 4.8, 95.2, 63.7, 0.0, 18.5, 17.8, 86.3, 0.0, 2.4, 11.3, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 72.6, 0.0, 12.1, 15.3, 85.5, 0.0, 2.4, 12.1)
my_values <- c(104, 0, 6, 14, 47, 0, 32, 45, 49, 0, 34, 41, 76, 0, 25, 23, 36, 68, 8, 12, 102, 0, 8, 14, 0, 0, 0, 124, 104, 0, 6, 14, 103, 0, 7, 14, 107, 0, 3, 14, 24, 0, 29, 71, 107, 0, 3, 14, 47, 58, 7, 12, 62, 0, 31, 31, 103, 0, 7, 14, 70, 0, 22, 32, 12, 0, 22, 90, 25, 80, 7, 12, 0, 0, 6, 118, 79, 0, 23, 22, 107, 0, 3, 14, 107, 0, 3, 14, 0, 0, 0, 124, 0, 0, 0, 124, 90, 0, 15, 19, 106, 0, 3, 15)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
