######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/mnt/storage-brno12-cerit/nfs4/home/andrea_kochova/BUSCO/8busco/summaries/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('8busco_072', '8busco_072', '8busco_072', '8busco_072', '8busco_058', '8busco_058', '8busco_058', '8busco_058', '8busco_035', '8busco_035', '8busco_035', '8busco_035', '8busco_011', '8busco_011', '8busco_011', '8busco_011', '8busco_024', '8busco_024', '8busco_024', '8busco_024', '8busco_075', '8busco_075', '8busco_075', '8busco_075', '8busco_039', '8busco_039', '8busco_039', '8busco_039', '8busco_061', '8busco_061', '8busco_061', '8busco_061', '8busco_044', '8busco_044', '8busco_044', '8busco_044', '8busco_065', '8busco_065', '8busco_065', '8busco_065', '8busco_048', '8busco_048', '8busco_048', '8busco_048', '8busco_016', '8busco_016', '8busco_016', '8busco_016', '8busco_054', '8busco_054', '8busco_054', '8busco_054', '8busco_008', '8busco_008', '8busco_008', '8busco_008', '8busco_069', '8busco_069', '8busco_069', '8busco_069', '8busco_056', '8busco_056', '8busco_056', '8busco_056', '8busco_046', '8busco_046', '8busco_046', '8busco_046', '8busco_068', '8busco_068', '8busco_068', '8busco_068', '8busco_001', '8busco_001', '8busco_001', '8busco_001', '8busco_059', '8busco_059', '8busco_059', '8busco_059', '8busco_063', '8busco_063', '8busco_063', '8busco_063', '8busco_028', '8busco_028', '8busco_028', '8busco_028', '8busco_026', '8busco_026', '8busco_026', '8busco_026', '8busco_006', '8busco_006', '8busco_006', '8busco_006', '8busco_033', '8busco_033', '8busco_033', '8busco_033', '8busco_023', '8busco_023', '8busco_023', '8busco_023', '8busco_012', '8busco_012', '8busco_012', '8busco_012', '8busco_057', '8busco_057', '8busco_057', '8busco_057', '8busco_002', '8busco_002', '8busco_002', '8busco_002', '8busco_041', '8busco_041', '8busco_041', '8busco_041', '8busco_032', '8busco_032', '8busco_032', '8busco_032', '8busco_074', '8busco_074', '8busco_074', '8busco_074', '8busco_017', '8busco_017', '8busco_017', '8busco_017', '8busco_014', '8busco_014', '8busco_014', '8busco_014', '8busco_005', '8busco_005', '8busco_005', '8busco_005', '8busco_009', '8busco_009', '8busco_009', '8busco_009', '8busco_045', '8busco_045', '8busco_045', '8busco_045', '8busco_003', '8busco_003', '8busco_003', '8busco_003', '8busco_027', '8busco_027', '8busco_027', '8busco_027', '8busco_030', '8busco_030', '8busco_030', '8busco_030', '8busco_047', '8busco_047', '8busco_047', '8busco_047', '8busco_073', '8busco_073', '8busco_073', '8busco_073', '8busco_034', '8busco_034', '8busco_034', '8busco_034', '8busco_071', '8busco_071', '8busco_071', '8busco_071', '8busco_060', '8busco_060', '8busco_060', '8busco_060', '8busco_021', '8busco_021', '8busco_021', '8busco_021', '8busco_051', '8busco_051', '8busco_051', '8busco_051', '8busco_077', '8busco_077', '8busco_077', '8busco_077', '8busco_031', '8busco_031', '8busco_031', '8busco_031', '8busco_064', '8busco_064', '8busco_064', '8busco_064', '8busco_053', '8busco_053', '8busco_053', '8busco_053', '8busco_037', '8busco_037', '8busco_037', '8busco_037', '8busco_038', '8busco_038', '8busco_038', '8busco_038', '8busco_052', '8busco_052', '8busco_052', '8busco_052', '8busco_007', '8busco_007', '8busco_007', '8busco_007', '8busco_050', '8busco_050', '8busco_050', '8busco_050', '8busco_042', '8busco_042', '8busco_042', '8busco_042', '8busco_062', '8busco_062', '8busco_062', '8busco_062', '8busco_022', '8busco_022', '8busco_022', '8busco_022', '8busco_055', '8busco_055', '8busco_055', '8busco_055', '8busco_067', '8busco_067', '8busco_067', '8busco_067', '8busco_004', '8busco_004', '8busco_004', '8busco_004', '8busco_036', '8busco_036', '8busco_036', '8busco_036', '8busco_070', '8busco_070', '8busco_070', '8busco_070', '8busco_020', '8busco_020', '8busco_020', '8busco_020', '8busco_029', '8busco_029', '8busco_029', '8busco_029', '8busco_013', '8busco_013', '8busco_013', '8busco_013', '8busco_043', '8busco_043', '8busco_043', '8busco_043', '8busco_040', '8busco_040', '8busco_040', '8busco_040', '8busco_066', '8busco_066', '8busco_066', '8busco_066', '8busco_010', '8busco_010', '8busco_010', '8busco_010', '8busco_076', '8busco_076', '8busco_076', '8busco_076', '8busco_018', '8busco_018', '8busco_018', '8busco_018', '8busco_049', '8busco_049', '8busco_049', '8busco_049', '8busco_025', '8busco_025', '8busco_025', '8busco_025', '8busco_015', '8busco_015', '8busco_015', '8busco_015', '8busco_019', '8busco_019', '8busco_019', '8busco_019')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(0.0, 0.0, 5.6, 94.4, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 79.0, 4.8, 4.8, 11.4, 0.0, 0.0, 0.0, 100.0, 82.3, 0.0, 6.5, 11.2, 0.0, 0.0, 0.0, 100.0, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 0.0, 100.0, 3.2, 0.0, 22.6, 74.2, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 65.3, 0.0, 20.2, 14.5, 83.1, 0.0, 5.6, 11.3, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.8, 0.0, 10.5, 88.7, 0.8, 0.0, 4.0, 95.2, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 19.4, 65.3, 5.6, 9.7, 58.9, 0.0, 25.0, 16.1, 19.4, 0.0, 41.9, 38.7, 64.5, 0.0, 22.6, 12.9, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 24.2, 59.7, 6.5, 9.6, 0.0, 0.0, 0.0, 100.0, 83.9, 0.0, 4.8, 11.3, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 85.5, 0.0, 2.4, 12.1, 73.4, 0.0, 13.7, 12.9, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.8, 99.2, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 2.4, 97.6, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 30.6, 0.0, 35.5, 33.9, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 42.7, 0.0, 34.7, 22.6, 86.3, 0.0, 2.4, 11.3, 0.0, 0.0, 0.8, 99.2, 83.9, 0.0, 4.8, 11.3, 0.0, 0.0, 0.0, 100.0, 48.4, 0.0, 28.2, 23.4, 55.6, 0.0, 29.8, 14.6, 29.0, 56.5, 4.8, 9.7, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.8, 99.2, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0)
my_values <- c(0, 0, 7, 117, 0, 0, 0, 124, 0, 0, 0, 124, 98, 6, 6, 14, 0, 0, 0, 124, 102, 0, 8, 14, 0, 0, 0, 124, 107, 0, 3, 14, 0, 0, 0, 124, 4, 0, 28, 92, 107, 0, 3, 14, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 81, 0, 25, 18, 103, 0, 7, 14, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 1, 0, 13, 110, 1, 0, 5, 118, 0, 0, 0, 124, 0, 0, 0, 124, 24, 81, 7, 12, 73, 0, 31, 20, 24, 0, 52, 48, 80, 0, 28, 16, 0, 0, 0, 124, 0, 0, 0, 124, 30, 74, 8, 12, 0, 0, 0, 124, 104, 0, 6, 14, 107, 0, 3, 14, 0, 0, 0, 124, 0, 0, 0, 124, 106, 0, 3, 15, 91, 0, 17, 16, 0, 0, 0, 124, 0, 0, 1, 123, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 3, 121, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 38, 0, 44, 42, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 53, 0, 43, 28, 107, 0, 3, 14, 0, 0, 1, 123, 104, 0, 6, 14, 0, 0, 0, 124, 60, 0, 35, 29, 69, 0, 37, 18, 36, 70, 6, 12, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 1, 123, 0, 0, 0, 124, 0, 0, 0, 124, 0, 0, 0, 124)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
